server:
  port: 8081
  
spring:
  mvc:
    view:
      prefix: "/"
      suffix: .jsp
  
  datasource:
    url: "jdbc:postgresql://localhost:5432/cafe"
    username: "postgres"
    password: "password"
#    driver-class-name: com.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 
   
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect


   
    
    
    